name: "compile"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: react-viewer-viewer
    - uses: actions/checkout@v2
      with:
        path: react-viewer
        repository: 152334H/react-viewer
      # at this point, at D:\a\react-viewer-viewer\react-viewer-viewer. The two repos are in cwd.
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: |
          react-viewer/package-lock.json
          react-viewer-viewer/package-lock.json
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install & build forked react-viewer
      run: cd react-viewer && npm ci && npm run build && cd ..
    - name: install viewer-viewer dependencies
      run: cd react-viewer-viewer && npm ci && cd ..
      # hopefully we can speed up future GAs by doing this
    - uses: actions/cache@v2
      with:
        path: |
          %USERPROFILE%/.cargo/bin/
          %USERPROFILE%/.cargo/registry/index/
          %USERPROFILE%/.cargo/registry/cache/
          %USERPROFILE%/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: # TODO: figure out how to set version correctly
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
        includeDebug: true
        projectPath: './react-viewer-viewer'
