name: "compile"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    steps:
    - name: ensure that env.USERPROFILE works
      run: | # copied from stackoverflow
        chcp 65001 #set code page to utf-8
        echo ("USERPROFILE=" + $env:USERPROFILE) >> $env:GITHUB_ENV
    - uses: actions/checkout@v2
    # get nodejs stuff
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install viewer-viewer Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install
    # js stuff is now installed. move on to rust stuff
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/cache@v2
      with:
        path: | # TODO: check if we're supposed to use backslashes or forward slashes here.
          ${{env.USERPROFILE}}\.cargo\bin\
          ${{env.USERPROFILE}}\.cargo\registry\index\
          ${{env.USERPROFILE}}\.cargo\registry\cache\
          ${{env.USERPROFILE}}\.cargo\git\db\
          src-tauri\target\
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: tauri-apps/tauri-action@dev #TODO: switch back to stable version when possible
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: # __VERSION__ refers to the number in src-tauri/tauri.conf.json
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "Probably broken"
        releaseDraft: true
        prerelease: true
    - uses: tauri-apps/tauri-action@dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-debug-v__VERSION__ 
        releaseName: "App debug v__VERSION__"
        releaseBody: "Debug build"
        releaseDraft: true
        prerelease: false
        args: "--debug"
