name: Deploy to github pages
on: 
  push:
    branches:
      master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: add hostname to package json
        run: sed 's/^}$/  ,"homepage": "https:\/\/152334h.github.io\/react-viewer-viewer\/"}/' -i package.json
      - name: Build viewer-viewer
        run: npm run build
      - name: Deploy to GH pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build
